# Basic
title: webbleen
subtitle: 
description: 昔我往矣，杨柳依依。今我来思，雨雪霏霏。
welcome_message: 嗨，我是李文斌。
creator: <a href="http://webbleen.com">@webbleen</a>

url: "http://webbleen.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: 简历, description: 我的简历, url: 'http://resume.webbleen.com'}
    # - {title: 标签, description: Tags, url: '#tag'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: wno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: togopaul
    github: webbleen
    # gitee: webbleen
    # twitter: webbleen
    # gplus: 107108267983477358170
    mail: webbleen@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
